import type { Metadata } from "next";
// 1. (유지) 기존 폰트 설정을 그대로 둡니다.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 2. (★추가★) 3단계에서 만든 AuthProvider를 import 합니다.
import { AuthProvider } from "@/contexts/AuthContext";

// (유지) 기존 폰트 변수 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// (유지) 기존 메타데이터
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 3. (★수정★)
          AuthProvider로 {children}을 감싸줍니다.
          이제 모든 {children} (페이지 컴포넌트)이 
          AuthContext의 값(로그인 상태 등)을 공유하게 됩니다.
        */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}